[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_URL = "https://tiptracker.ai"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"
  NEXT_USE_TRAILING_SLASH = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Actual Supabase credentials (will be overridden by environment variables in Netlify dashboard if set)
  NEXT_PUBLIC_SUPABASE_URL = "https://bggsscexogsptcnnwckj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3NzY2V4b2dzcHRjbm53Y2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjgwMDQsImV4cCI6MjA1Njk0NDAwNH0.yRmBEA5ddBqoM-N9iOjQpyMtxQcBlbEUJ-diV396J94"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".env.local"]

# Ensure CSS is properly processed
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Stripe webhook
[[redirects]]
  from = "/api/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 