[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_URL = "https://tiptracker.ai"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"
  NEXT_USE_TRAILING_SLASH = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Actual Supabase credentials (will be overridden by environment variables in Netlify dashboard if set)
  NEXT_PUBLIC_SUPABASE_URL = "https://bggsscexogsptcnnwckj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3NzY2V4b2dzcHRjbm53Y2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjgwMDQsImV4cCI6MjA1Njk0NDAwNH0.yRmBEA5ddBqoM-N9iOjQpyMtxQcBlbEUJ-diV396J94"

# Use the Next.js plugin to handle server-side rendering
[[plugins]]
  package = "@netlify/plugin-nextjs"

# No need for custom redirects - the plugin handles this

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 