[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_URL = "https://tiptrackerai.netlify.app"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,STRIPE_SECRET_KEY,STRIPE_PUBLISHABLE_KEY,STRIPE_WEBHOOK_SECRET,STRIPE_MONTHLY_PRICE_ID,STRIPE_ANNUAL_PRICE_ID"
  NEXT_USE_TRAILING_SLASH = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  # Actual Supabase credentials (will be overridden by environment variables in Netlify dashboard if set)
  NEXT_PUBLIC_SUPABASE_URL = "https://bggsscexogsptcnnwckj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3NzY2V4b2dzcHRjbm53Y2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjgwMDQsImV4cCI6MjA1Njk0NDAwNH0.yRmBEA5ddBqoM-N9iOjQpyMtxQcBlbEUJ-diV396J94"
  # Stripe credentials should be set in the Netlify dashboard
  STRIPE_SECRET_KEY = ""
  STRIPE_PUBLISHABLE_KEY = ""
  STRIPE_WEBHOOK_SECRET = ""
  STRIPE_MONTHLY_PRICE_ID = ""
  STRIPE_ANNUAL_PRICE_ID = ""

# No need for the Next.js plugin with static export
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Force all page requests to use HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Specific redirects for each route to ensure they work consistently
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/signin"
  to = "/signin.html"
  status = 200
  force = true

[[redirects]]
  from = "/signin/*"
  to = "/signin.html"
  status = 200
  force = true

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200
  force = true

[[redirects]]
  from = "/signup/*"
  to = "/signup.html"
  status = 200
  force = true

[[redirects]]
  from = "/history"
  to = "/history.html"
  status = 200
  force = true

[[redirects]]
  from = "/history/*"
  to = "/history.html"
  status = 200
  force = true

[[redirects]]
  from = "/analytics"
  to = "/analytics.html"
  status = 200
  force = true

[[redirects]]
  from = "/analytics/*"
  to = "/analytics.html"
  status = 200
  force = true

[[redirects]]
  from = "/upgrade"
  to = "/upgrade.html"
  status = 200
  force = true

[[redirects]]
  from = "/upgrade/*"
  to = "/upgrade.html"
  status = 200
  force = true

[[redirects]]
  from = "/tips"
  to = "/tips.html"
  status = 200
  force = true

[[redirects]]
  from = "/tips/*"
  to = "/tips.html"
  status = 200
  force = true

[[redirects]]
  from = "/premium-dashboard"
  to = "/premium-dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/premium-dashboard/*"
  to = "/premium-dashboard.html"
  status = 200
  force = true

# For all other routes, serve the corresponding HTML file first
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  force = false

# If the HTML file doesn't exist, fall back to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 