name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create environment variables for build
      run: |
        echo "NEXT_PUBLIC_SUPABASE_URL=https://bggsscexogsptcnnwckj.supabase.co" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ3NzY2V4b2dzcHRjbm53Y2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjgwMDQsImV4cCI6MjA1Njk0NDAwNH0.yRmBEA5ddBqoM-N9iOjQpyMtxQcBlbEUJ-diV396J94" >> .env.local
        echo "STRIPE_SECRET_KEY=dummy-key" >> .env.local
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=dummy-key" >> .env.local
        echo "STRIPE_MONTHLY_PRICE_ID=price_dummy" >> .env.local
        echo "STRIPE_ANNUAL_PRICE_ID=price_dummy" >> .env.local
        echo "NEXT_PUBLIC_URL=http://localhost:3000" >> .env.local

    - name: Build
      run: npm run build --if-present
      
    # Skipping lint step as it's now handled in next.config.js
    # - name: Lint
    #   run: npm run lint --if-present 