name: Next.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create dummy environment variables
      run: |
        echo "NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy-key" >> .env.local
        echo "STRIPE_SECRET_KEY=dummy-key" >> .env.local
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=dummy-key" >> .env.local
        echo "STRIPE_MONTHLY_PRICE_ID=price_dummy" >> .env.local
        echo "STRIPE_ANNUAL_PRICE_ID=price_dummy" >> .env.local
        echo "STRIPE_WEBHOOK_SECRET=whsec_dummy" >> .env.local
        echo "NEXT_PUBLIC_URL=http://localhost:3000" >> .env.local
    
    - name: Build
      run: npm run build